// Generated types placeholder
// This file is auto-generated by the build process

export interface SupportedLocale {
  [key: string]: string;
}

export interface ThemeValue {
  [key: string]: string;
}

export interface PipelineStore {
  [key: string]: any;
}

export interface MetricsStore {
  [key: string]: any;
}
