// Generated types placeholder
// This file is auto-generated by the build process

export type SupportedLocale = 'en' | 'zh';
export type ThemeValue = 'light' | 'dark' | 'auto';

export interface OutboxRecord {
  id: string;
  status: OutboxStatus;
  [key: string]: any;
}

export type OutboxStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'terminal_failed';

export type CircuitState = 'closed' | 'open' | 'half-open';

export interface PipelineStage {
  name: string;
  duration: number;
  [key: string]: any;
}

export interface MetricSnapshot {
  timestamp: number;
  value: number;
  [key: string]: any;
}

export interface MetricAlert {
  id: string;
  message: string;
  [key: string]: any;
}

export interface PipelineStore {
  stages: PipelineStage[];
  totalDuration: number;
  confidence: number;
  intercepted: boolean;
  circuitState: string;
  blockingQueueDepth: number;
  subscribe: (callback: Function) => void;
  [key: string]: any;
}

export interface MetricsStore {
  metrics: MetricSnapshot[];
  history: MetricSnapshot[];
  alerts: MetricAlert[];
  hasAlerts: boolean;
  subscribe: (callback: Function) => void;
  [key: string]: any;
}
